# Generated by Django 4.2.5 on 2023-12-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="employee", name="id",),
        migrations.AlterField(
            model_name="employee",
            name="eid",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="employee",
            name="eprofilephoto",
            field=models.FileField(blank=True, null=True, upload_to="profile_photo/"),
        ),
        migrations.AlterModelTable(name="employee", table="employees",),
    ]
