# Generated by Django 4.2.5 on 2023-12-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0002_remove_employee_id_alter_employee_eid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="econtact",
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="eid",
            field=models.IntegerField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="employee", name="ename", field=models.CharField(max_length=55),
        ),
    ]
