# Generated by Django 4.2.5 on 2023-12-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0004_alter_employee_eid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="eprofilephoto",
            field=models.FileField(default="eprofilephoto", upload_to="profile_photo/"),
        ),
    ]
