# Generated by Django 4.2.5 on 2023-12-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0005_alter_employee_eprofilephoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="eprofilephoto",
            field=models.FileField(upload_to="profile_photo/"),
        ),
    ]
